// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_0;

namespace project_0.Migrations
{
    [DbContext(typeof(StoreAppContext))]
    [Migration("20201228022021_TestMigration")]
    partial class TestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("project_0.Customer", b =>
                {
                    b.Property<Guid>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("favstore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer_Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("project_0.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("productId")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<double>("sale")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("productId");

                    b.ToTable("ItemsAtStore");
                });

            modelBuilder.Entity("project_0.OrderedItem", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("itemId")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("itemId");

                    b.ToTable("orderedItems");
                });

            modelBuilder.Entity("project_0.Orders", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<Guid?>("Customer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("stroeLocationId")
                        .HasColumnType("int");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.HasKey("orderID");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("stroeLocationId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("project_0.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("project_0.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalSales")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("project_0.Item", b =>
                {
                    b.HasOne("project_0.Store", null)
                        .WithMany("ItemList")
                        .HasForeignKey("StoreId");

                    b.HasOne("project_0.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("project_0.OrderedItem", b =>
                {
                    b.HasOne("project_0.Item", "item")
                        .WithMany()
                        .HasForeignKey("itemId");

                    b.Navigation("item");
                });

            modelBuilder.Entity("project_0.Orders", b =>
                {
                    b.HasOne("project_0.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("Customer_Id");

                    b.HasOne("project_0.Store", "stroeLocation")
                        .WithMany("orders")
                        .HasForeignKey("stroeLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("stroeLocation");
                });

            modelBuilder.Entity("project_0.Store", b =>
                {
                    b.Navigation("ItemList");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
